flame2023_kwargs:
  model_path: /media/ankarako/data/dev/phd/3dmms/FLAME2023/assets/flame2023.pkl
  mesh_path: /media/ankarako/data/dev/phd/3dmms/FLAME2023/assets/head_template_mesh.obj
  masks_path: /media/ankarako/data/dev/phd/3dmms/FLAME2023/assets/FLAME_masks.pkl
  lmk_embedding_with_eyes_path: /media/ankarako/data/dev/phd/3dmms/FLAME2023/assets/landmark_embedding_with_eyes.npy
  nid_params: 300
  nex_params: 100
  add_teeth: false

ict_model_kwargs:
  data_root: /media/ankarako/data/dev/phd/3dmms/ICT-FaceKit/FaceXModel
  skinning_weights: false

output_dir: .output
device: [0]

nrigid_iters: 5000
lr: 1.0e-3
w_data: 1.0
w_edge: 0.1
w_laplacian: 0.1
w_normal: 0.0001
w_lmks: 100.0
knn_k: 10
update_correspondences_every: 1